### ISSUE TITLE
how do I get a value from a map that's been recursively merged?

### ISSUE THREAD

**Issue by sturobson** [pentzzsolt/sass-recursive-map-merge#11]
Hi, 

This looks perfect for my current needs creating a cohesive taxonomy and set of variables to be used within a design system.

I think I have a couple of maps merged successfully -- how do I get the required value from the new map?

Here's the maps so far:

```
$extra-small: (
  'font-size': 12px,
  'font-weight': 400,
  'line-height': 1.4
);
$small: (
  'font-size': 14px,
  'font-weight': 300,
  'line-height': 1.5
);

$regular: (
  'font-size': 18px,
  'font-weight': 500,
  'line-height': 1.35,
);

$sans: recursive-map-merge(
  $extra-small,
  $small,
  $regular
);
```

**Comment by pentzzsolt** [comment]
I am not quite sure what you want to achieve here, but let me first point out that `recursive-map-merge()` can only take two arguments and two exactly, it is not going to work with more than that. If that's an actual need, you can open a separate issue and I will take a look.

Now in your example code, if you try merging `$extra-small` with `$small` for example, you will end up with the following map:

```scss
$sans: (
    font-size: 14px,
    font-weight: 300,
    line-height: 1.5
);
```

Which I hardly think is your goal here. All you need to do is rework your code a little bit.

```scss
$sans: (
    extra-small: (
        font-size: 12px,
        font-weight: 400,
        line-height: 1.4
    ),
    small: (
        font-size: 14px,
        font-weight: 300,
        line-height: 1.5
    ),
    regular: (
        font-size: 18px,
        font-weight: 500,
        line-height: 1.35,
    )
);
```

In fact, `recursive-map-merge()` isn't even necessary here. It comes handy when you have multiple multidimensional maps containing similar data with a matching structure. If you stored the `font-size` and `line-height` values in separate maps for example.

```scss
$font: (
    extra-small: (
        font-size: 12px,
        font-weight: 400
    ),
    small: (
        font-size: 14px,
        font-weight: 300
    ),
    regular: (
        font-size: 18px,
        font-weight: 500
    )
);

$line: (
    extra-small: (
        line-height: 1.4
    ),
    small: (
        line-height: 1.5
    ),
    regular: (
        line-height: 1.35,
    )
);

$sans: recursive-map-merge($font, $line);
```

And this would result in the same map that I showed previously. Now, to your original question of getting the values out, you need to use Sass' built-in [`map-get()`](http://sass-lang.com/documentation/Sass/Script/Functions.html#map_get-instance_method) function. In the above cases, you have a multidimensional map, so the thing is a little more tricky.

```scss
.regular {
    font-size: map-get(map-get($sans, regular), font-size);
}
```

`map-get($sans, regular)` gives you back the map _inside_ the map, which you also need to call `map-get()` on to get the exact property you are looking for.

**Comment by pentzzsolt** [comment]
Unless there is anything further I can help you with, I will close this tomorrow.
